@host=https://localhost:7056/

POST {{host}}/auth/register

Content-Type: application/json

{
    "firstname": "ola",
    "lastname": "nordmann",
    "email": "ola@nordmann.com",
    "password": "testpass"
}


